FORMAT: 1A
HOST: http://private-adf3e-greenway.apiary-mock.com/

# Greenway

Authoring Learning Objectives.

## Chapters [/chapters]

### List All Chapters [GET]

+ Response 200 (application/json)

        {
            "chapters": [
                {
                    "_links": {
                        "self": { "href": "http://private-adf3e-greenway.apiary-mock.com/chapters/ec70fc50-2be3-4548-b71d-326460cb2f72" }
                    },
                    "id": "ec70fc50-2be3-4548-b71d-326460cb2f72",
                    "title": "Algebra",
                    "number": "2",
                    "createdAt": "2012-04-23T18:25:43.511Z",
                    "percentComplete": 100
                }, 
                {
                    "_links": {
                        "self": { "href": "http://private-adf3e-greenway.apiary-mock.com/chapters/e5b5fe27-8dd2-45af-bcd0-1b60d8608882" }
                    },
                    "id": "e5b5fe27-8dd2-45af-bcd0-1b60d8608882",
                    "title": "Pre-Calculus",
                    "number": "6",
                    "createdAt": "2012-04-23T18:25:43.511Z",
                    "percentComplete": 30
                }
            ]
        }
        

## Chapter [/chapters/{chapterId}]

### Retrieve Chapter [GET]

+ Parameters
    + chapterId (string) - ID of the Chapter in the form of an alphanumeric ID.

+ Response 200 (application/json)

        {
            "_links": {
                "self": { "href": "http://private-adf3e-greenway.apiary-mock.com/chapters/{chapterId}" },
                "pdf": { "href": "http://private-adf3e-greenway.apiary-mock.com/pdfs/06c1cea0-b985-4bf0-ba04-cf0493fcb165.pdf" }
            },
            "id": "{chapterId}",
            "title": "Applications of Integration",
            "number": "6",
            "createdAt": "2012-04-23T18:25:43.511Z",
            "percentComplete": 30,
            "sections": [
                {
                    "_links": {
                        "self": { "href": "http://private-adf3e-greenway.apiary-mock.com/chapters/{chapterId}/sections/6.1" },
                        "objectives": { "href": "http://private-adf3e-greenway.apiary-mock.com/chapters/{chapterId}/sections/6.1/objectives" }
                    },
                    "title": "Velocity and Net Change",
                    "number": "6.1",
                    "completion": {
                        "completed": 6,
                        "total": 72
                    }
                },
                {
                    "_links": {
                        "self": { "href": "http://private-adf3e-greenway.apiary-mock.com/chapters/{chapterId}/sections/6.2" },
                        "objectives": { "href": "http://private-adf3e-greenway.apiary-mock.com/chapters/{chapterId}/sections/6.2/objectives" }
                    },
                    "title": "Regions Between Curves",
                    "number": "6.2",
                    "completion": {
                        "completed": 36,
                        "total": 74
                    }
                }
            ]
        }
    

## Section [/chapters/{chapterId}/sections/{sectionId}]

### Retrieve Section [GET]

+ Parameters
    + sectionId (string) - ID of the Section in the form of a string.

+ Response 200 (application/json)

        {
            "_links": {
                "self": { "href": "http://private-adf3e-greenway.apiary-mock.com/chapters/{chapterId}/sections/{sectionId}" },
                "objectives": { "href": "http://private-adf3e-greenway.apiary-mock.com/chapters/{chapterId}/sections/{sectionId}/objectives" }
            },
            "id": "{sectionId}",
            "title": "Velocity and Net Change",
            "number": "6.1",
            "completion": {
                "completed": 1,
                "total": 72
            },
            "objectives": [
                {
                    "number": "1",
                    "content": "Review properties of velocity and net change.",
                    "exerciseIds":[
                        "ffffffff55ac48f0e4b0c679d51ee134"
                    ],
                    "rating": 79,
                    "ratingSuggestions": [
                        {
                            "message": "Mauris sed orci varius dui ultricies dignissim.",
                            "documentation": "http://private-adf3e-greenway.apiary-mock.com/standards/objectives/VB31",
                            "priority": 8
                        },
                        {
                            "message": "Donec a magna id nulla iaculis dapibus.",
                            "documentation": "http://private-adf3e-greenway.apiary-mock.com/standards/objectives/WD22",
                            "priority": 3
                        }
                    ]
                }
            ],
            "exercises": [
                {
                    "number": "1",
                    "id":"ffffffff55ac48f0e4b0c679d51ee133",
                    "content": "Explain the meaning of position, displacement, and distance traveled as they apply to an object moving along a line.",
                    "svgId": "page10"
                },
                {
                    "number": "4",
                    "id":"ffffffff55ac48f0e4b0c679d51ee134",
                    "content": "Explain how to use definite integrals to find the net change in a quantity, given the rate of change of that quantity.",
                    "svgId": "page10"
                }
            ],
            "svgs": [
                "<svg id='page10' width='891px' height='1111.8130434782609px' version='1.1' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink'></svg>"
            ]
        }
        
## Section Objectives [/chapters/{chapterId}/sections/{sectionId}/objectives]

### Update Section Objectives [PUT]

Send a PUT request containing all of the objectives you want the section to have linked to the exercises in the section (by exercise ID).  No need to send rating or ratingSuggestions properties (they will be ignored).

+ Parameters
    + chapterId (string) - ID of the Chapter in the form of an alphanumeric ID.
    + sectionId (string) - ID of the Section in the form of a string.

+ Request (application/json)

        {
            "objectives": [
                {
                    "number": "1",
                    "content": "Review properties of velocity and net change.",
                    "exerciseIds": [ "ffffffff55ac48f0e4b0c679d51ee134" ]
                }
            ]
        }

+ Response 200 (application/json)

## Exercise Objective Recommendations [/chapters/{chapterId}/sections/{sectionId}/recommend?limit={limitSize}]

### Retrieve Objective Recommendations [POST]

+ Parameters
    + chapterId (string) - ID of the Chapter in the form of an alphanumeric ID.
    + sectionId (string) - ID of the Section in the form of a string.
    + limitSize (number) - Max number of recommendations to return.

+ Request (application/json)

        {
            "exercise": {
                "content": "Explain how to use definite integrals to find the net change in a quantity, given the rate of change of that quantity."
            }
        }

+ Response 200 (application/json)

        {
            "recommendations": [
                {
                    "content": "Review properties of velocity and net change.",
                    "rating": 68,
                    "ratingSuggestions": [
                        {
                            "message": "Mauris sed orci varius dui ultricies dignissim.",
                            "documentation": "http://private-adf3e-greenway.apiary-mock.com/standards/objectives/VB31",
                            "priority": 8
                        },
                        {
                            "message": "Donec a magna id nulla iaculis dapibus.",
                            "documentation": "http://private-adf3e-greenway.apiary-mock.com/standards/objectives/WD22",
                            "priority": 3
                        }
                    ]
                }, 
                {
                    "content": "Solve applications involving net change and future value.",
                    "rating": 92,
                    "ratingSuggestions": [
                        {
                            "message": "Mauris sed orci varius dui ultricies dignissim.",
                            "documentation": "http://private-adf3e-greenway.apiary-mock.com/standards/objectives/VB31",
                            "priority": 8
                        },
                        {
                            "message": "Donec a magna id nulla iaculis dapibus.",
                            "documentation": "http://private-adf3e-greenway.apiary-mock.com/standards/objectives/WD22",
                            "priority": 3
                        }
                    ]
                },
                {
                    "content": "Find position and velocity from acceleration.",
                    "rating": 37,
                    "ratingSuggestions": [
                        {
                            "message": "Mauris sed orci varius dui ultricies dignissim.",
                            "documentation": "http://private-adf3e-greenway.apiary-mock.com/standards/objectives/VB31",
                            "priority": 8
                        },
                        {
                            "message": "Donec a magna id nulla iaculis dapibus.",
                            "documentation": "http://private-adf3e-greenway.apiary-mock.com/standards/objectives/WD22",
                            "priority": 3
                        }
                    ]
                }
            ]
        }